services:
  postgres:
    container_name: postgres_14dc499f
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres